import argparse

parser = argparse.ArgumentParser(description="Process the files generated by pygmentize.")
parser.add_argument('inputfiles', metavar='i', type=str, nargs='+', help="Input HTML file to process.")

args = parser.parse_args()

for html in args.inputfiles:
    rawHTML = open(html, 'r')
    preStrip = rawHTML.readlines()
    rawHTML.close()
    firstPass = preStrip[77:]
    final = firstPass[:-2]
    toWrite = "".join(final)
    outFile = open("procd_" + html, "w")
    outFile.write(toWrite)
    outFile.close()
